# Project Organization {#projects}

-   *If I copied this whole folder onto someone else's computer, could
    they pick up the project?*
-   *Are the folder organization and file naming clear?*

We aim to organize projects in a self-contained way, with clear
separation between raw data, processed data, exploratory analyses, and
final products.

-   Some exceptions for large data sets or rapidly changing data sets.
    In these cases, data can be organized as a separate folder
    or poject.
    -   In many cases it is actually best for data to be organized as a
        *separate project* from analysis. This allows multiple analysis
        projects to rely on the same upstream data project, avoiding
        multiple versions of data. In these cases the "data" project
        should include raw data, aggregation and cleaning, and its
        output will be cleaned but complete (not summarized data).
        Analysis projects can import this data as a first step.

### Learn

-   Here is [a nice blog post about project
    structure](http://nicercode.github.io/blog/2013-05-17-organising-my-project/)
    and a few more
    [alternatives](https://discuss.ropensci.org/t/resources-on-project-directory-organization/340).
-   For anything using R, [RStudio
    projects](https://support.rstudio.com/hc/en-us/articles/200526207-Using-Projects)
    are a good idea for project organization. Here's a [Software
    Carpentry Lesson on RStudio
    projects](http://swcarpentry.github.io/r-novice-gapminder/02-project-intro/).
