
# High-Performance Servers

*How can I make this giant beast of a model run faster?*

-   Our Aegypti server has 40 cores and 250G of RAM, and can be accessed from
    anywhere, and has and easy-to-use RStudio interface. It's a good go-to for
    most biggish analyses you might do.
-   The server is generally most useful if you can parallelize your R code
    across many processors . It's also useful if you have jobs that need a large
    amount of memory (often big geospatial analyses), or just something that
    needs to run all weekend while your computer does other things.
-   We have an \#eha-servers Slack room, for coordinating use of this and other
    servers. Check in there if you have questions or before running a big job.
-   There is no privacy on Aegypti - system admins can, and do, go into everyone's
    file systems for maintenance purposes.
-   We also have accounts for Amazon Web Services for appropriate projects.

<div style="width: 100%; text-align: center;">

<div data-netdata="system.cpu" data-dimensions="user"
data-chart-library="easypiechart" data-easypiechart-max-value="100"
data-units="%" data-width="150px" data-after="-60" data-points="60"
data-title="CPU Usage" data-units="%" data-colors="#FF5555">

</div>

<div data-netdata="system.ram" data-dimensions="used|buffers|active|wired"
data-append-options="percentage" data-chart-library="easypiechart"
data-title="RAM Usage" data-units="%" data-easypiechart-max-value="100"
data-width="150px" data-after="-60" data-points="60" data-colors="#66AA00">

</div>

<div data-netdata="disk_space._" data-title="Hard Disk Usage"
data-append-options="percentage" data-decimal-digits="0" data-dimensions="used"
data-chart-library="easypiechart" data-width="150px" data-after="-60"
data-points="60" data-easypiechart-max-value="100" data-units="%">

</div>

<script type="text/javascript" src="http://aegypti.ecohealthalliance.org:22051/status/dashboard.js"></script>

</div>

## Install

-   Contact [Noam](mailto:ross@ecohealthalliance.org) for access to this machine
    and he will create an account and password for you and give you further
    instructions.
-   Log on to the RStudio server interface by pointing your browser at
    http://aegypti.ecohealthalliance.org:8787/. For SSH-based access just use
    `ssh aegypti.ecohealthalliace.org` from the terminal.
-   You will use GitHub to move project work back and forth from your local
    machine. You will need to setup GitHub access from this machine using SSH
    keys as described in [Happy Git with R Chapter
    12](http://happygitwithr.com/ssh-keys.html). You'll also have to set up your
    tokens [Appendix B](http://happygitwithr.com/github-pat.html) again.

## Learn

-   [Chapter 7.4 of *Efficient
    R*](https://csgillespie.github.io/efficientR/performance.html#performance-parallel)
    provides a brief introduction to parallelization.
-   Not everything can be done from the RStudio server interface on the server.
    If you are not familiar with the shell interface, brush up via [this
    Software Carpentry lesson](http://swcarpentry.github.io/shell-novice/).  Here's a useful
    [cheat sheet](https://www.git-tower.com/blog/command-line-cheat-sheet/) on the topic.
-   Look
    at this [chapter](http://v4.software-carpentry.org/shell/ssh.html) from an
    old version of the lesson for instructions on using the Secure Shell (SSH)
    to login to the server remotely and setting up keys so you don't have to
    enter your password every time.
-   Other helpful things you might look into are [tmux](https://tmux.github.io/)
    for keeping shell processes running when you log off (already installed),
    and [SSH config
    files](http://nerderati.com/2011/03/17/simplify-your-life-with-an-ssh-config-file/)
    for simplifying shell logon.

## Cloud computing with Amazon Web Services

-  EHA has an organizational Amazon Web Services account that may be useful for some
   projects.  AWS S3 storage is useful for hosting large data files.  AWS EC2 cloud
   computers may be appropriate for a hosting a web app or database, automating regular processes,
   or other analytical projects.
-  Contact Noam for access to the AWS account, to discuss whether AWS will be
   useful for your project, or to discuss other cloud resources.
-  All resources used on AWS need to be tagged with a `project:PROJECTNAME` tag
   in order to assign costs to the appropriate EHA projects.
-  Be judicious with AWS service usage.  It is easy to run up costs.

## Being a good neighbor

- Aegypti is a shared EHA resource, so good communication and responsible use are paramount to keeping it up and running smoothly for all of us. As mentioned before, we have an \#eha-servers Slack room, for coordinating use of our servers. Check in there if you have questions or before running a big job.

### Hard Disk Space Limits
- We have a lot of RAM (256GB!), but in general, we need at least as much free disk space as RAM, since RStudio keeps temporary copies of your R session on-disk in case of a crash. We have a relatively small disk (1 TB), because it is a very high performance SSD.
    - It is very easy to generate LOTS of temporary data so take that into consideration. This is especially true for spatial analyses using raster files. The default settings on aegypti have been configured to delete these raster temp files quickly, but keep this in mind if you are performing spatial analyses and are running out of hard disk space -- raster temp files may be the culprit.
    - Aegypti is for temporary, in-progress projects, not long-term storage:
        - Keep project code on Github.
        - Use a shared directory, `storr`, or GRASS GIS for big shared data sets.
        - Unused files need to be downloaded and stored locally or on our NAS backup.
    - There are several memory-related points to keep in mind when using RStudio on Aegypti:
        - `.Rdata` files can take up a lot of space. You can explicitly save important objects you create individually with `saveRDS(object, "filename")` and load them with `objects <- readRDS("filename")`.
        - `.Rproj.user` directories in each of your R projects hold large clones of your sessions. They might be orphaned after a session crash -- these files can be safely deleted.
        - In general, your RStudio options should NOT save your environment. 
- To explore your Aegypti directories and manage your large files, you can use `ncdu` from the terminal.

### Managing RAM Usage
- Aegypti has a lot of RAM (256GB), but with several projects running at once, we sometimes reach this upper limit. When we do hit the upper limit, the next process that requests memory over that limit will likely be the process that gets terminated. This means that if you run a very large job and are not aware of current memory usage, you may accidentally trigger the termination of someone else's process -- a process that might have been running for hours, days, or weeks!
- For this reason, it's good to know how much RAM is currently in use, and how much you think you will be using:
    - To check on the current state of Aegypti, use `htop` by typing `htop` into an aegypti-connected terminal window. This program graphically shows the status of all 40 cores, along with the amount of RAM in use and all the processes currently being run.
- When thinking about how much RAM you might need, remember that many implementations of paralellized code will make copies of the objects being manipulated to send to each core. This potentially multiplies your RAM usage by the number of cores you run on: if you were only using 8GB, but parallelize to 20 cores, you could end up taking up 160GB of space! Before running a large job over many cores, it makes sense to take a look at its memory footprint on just one core. As always, if you need advice
- Your RStudio environment can take up considerable RAM, so please clear it when not in use. Exiting the browser window from an RStudio session will not immediately quit your session, and you will still be holding on to memory from the objects in your environment. To explicitly exit your RStudio session in a browser, go to `File -> Quit Session` in the menu bar. This will quit your session and free up RAM space for other users. 




