# Airtable {#airtable}

This chapter will provide an overview of Airtable and good practices for designing data models in relational databases. 

## Key Terms

- **Workspace** - A collection of bases that a user has access to.
- **Base** - A database. Each is identified by the airtable API via a `base id` 
- **Table** - A tabular data set within a base. Each table is identified by the airtable API via the name of the table e.g. "Demo Table"
- **Record** - An individual cell within a table. Each record is identified by the airtable API via a `record id`
- **Field** - A property of data in a table 
- **Views** - A specific way of displaying a table. Default is grid. 
- **Entity** - Something that either physically or logically exists whose properties are typically stored in a table and composed of data elements (a table).
- **Element** - an attribute of a Entity (a field)

## What is Airtable?

Airtable provides a cloud hosted spreadsheet-database hybrid platform for collaborative data curation. The platform is designed to provide features of a relational database (SQL-Like) linked records with an easy-to-use spreadsheet interface. What is more, each database provides a data service that can be accessed via a secure application programming interface (API) by authorized users. This combination of features make Airtable an appropriate platform for people conducting data entry as well as people building technical infrastructure.  

## When should I use Airtable? 

Use Airtable when you would have multiple tabs in a spreadsheet, when you have hierarchical data, and/or when you want to create collaborative automated workflows in a low code environment. 

**Project Management**  
Because Airtable is extremely useful and user friendly, there are a plethora of pre-built templates for nearly an project management type task.  
- [Airtable Templates](https://www.airtable.com/templates)  
- [User Contributed Templates](https://www.airtable.com/universe)  

For example, the computational sciences team has had success using  Airtable for candidate searches. Airtable allows us to efficiently, independently, and consistently review applications then compare our ratings. We can then sort candidates by average score and reach a consensus on who to follow up with. 

**Research Data**  
Airtable shines when you have multiple data entities that are linked via common data elements. For example, if you are sampling bats then conducting antibody screening, running multiplex PCR, and keeping physical samples of blood and urine from those bats, you have multiple data entities (bats, antibody test results, pcr test results, and physical samples) that are all linked via common data elements like site and collector.
What is more, the test results depend on the physical samples and the physical samples depend on the bats. Those common data elements only need to be entered into a single entity (or table) then shared across the other entities in your base using linked elements. Once you have linked elements you no longer have to worry about updating the same piece of information in multiple locations and you can quickly navigate between entities and understand hierarchical relationships. 

```{r diagram, echo=FALSE, fig.height=8, fig.cap="Data model for bat sampling example."}
DiagrammeR::grViz("
digraph bat_sampling {

  # a 'graph' statement
  graph [overlap = true, nodesep = .5, ranksep = .25, compound = true, color = MediumAquamarine, fontsize = 10]

  # 'node' styling
  node [shape = circle,
        fixedsize = true,
        width = 1,
        fontname = Helvetica,
        style = filled,
        fillcolor = MediumAquamarine]
        
  a [label = 'Collector']
  b [label = 'Site']
  c [label = 'Bat']
  d [label = 'Antibody\ntest result']
  e [label = 'PCR\ntest result']
  f [label = 'Physical\nsample']
  
  edge [color = grey, 
        arrowhead = none,
        arrowtail = none,
        penwidth = 3]
 
 a -> c [label = 'Collected by']
 b -> c [label = 'Collected at']
 c -> f [label = 'Collected from']
 f -> d [label = 'Derived from']
 f -> e [label = 'Derived from']
 
}
  
")

```  


## Security and Access Control

At the platform level, Airtable follows industry best practices for security. Airtable maintains physical and technological security as part of its ISO IEC 27001:2013 and SOC 2 compliance measures.  Data are 256-bit encrypted when storing on the server and also when transferring data over the internet. To find vulnerabilities in their software, they run daily, weekly, and monthly scans on different components of their system and regularly commission external penetration tests. They also run a bug bounty program to help identify issues. Their data centers have fire detection and suppression systems, redundant power systems, and strict control for physical access. Because Airtable relies on Amazon Web Services (AWS) for its cloud infrastructure (the same providers used by previous EHA projects), data are geo-redundantly replicated in backups across multiple zones to increase data durability. They also have a team monitoring services at all times. Airtable employees are thoroughly vetted before hiring and continually trained on data protection best practices. Their workstations are secured by using full-disk encryption, automatic locking, and strong password requirements.  

### User- and Administrator Security Features
#### Access Controls

Airtable provides database (referred to as "base") and workspace administrators with granular controls over who can view, edit, comment, or otherwise modify data at the base, table, and field levels.  There are four levels of Airtable user permissions:  

- **Owner/Creator**: Full administrative control of base  
- **Editor**: Sees full base, create and modify records and views, create and modify view share links  
- **Commenter**:  Sees full base, comment on records  
- **Reader**: Sees full base  

Direct access to a base or workspace is granted or removed by base owners and creators to Airtable users. Base owners and creators can control who has access to a base and can control any “share” links created for that base. They may also restrict editing of tables or fields within a base. Any collaborator given direct access to a base at any permission level will be able to duplicate that base and share that data further. It is important that direct access to the base is limited to individuals with a need to curate or analyze the data. 
To further restrict access to a base, users can be given indirect access via revocable share links. These can be customized to prevent users from seeing the full base, prevent duplicating the base, and prevent copying data from the base. The ability to use the link can be password protected, restricted to people with certain email domains, and may be revoked at any time. If there are concerns about data leaks via base or table duplication, inviting people with a need to view the data via share links constrains their ability to extract data from the base.


## Importing data

## Using the API

## Automating Airtable

## Airtable and R

## Base Design Process

### Workflow Summary

0) Describe what the database will do and collect use cases
1) Determine the roles of various stakeholders
1) List out the entities in the database and define their properties
2) Map out how  the entities fit together (which properties link them)
3) Check that the mapping meets the use cases
4) Build base in Airtable
5) Check that the base meets the use cases

## Main content

This is how we answered the question...

### Section 1

### Section 2

### Section N

## Additional Resources

To learn more about the topic, check out these resources

- Resource 1 - short description of linked resource
- Resource N - short description of linked resource


