# GitHub Actions

[GitHub Actions](https://docs.github.com/en/actions) allows automation, customisation, and execution of your research project workflows right in your GitHub repository. 

In gist, [GitHub Actions](https://docs.github.com/en/actions) is a *workflow* composed of a *job* or a number of *jobs*. The *job/s* are then composed of *steps* that control the order in which *actions* are run in order to complete a *job/s*. This *workflow* is scheduled or triggered by a specific *event* and runs on what is called a *runner* - a server that has the [GitHub Actions](https://docs.github.com/en/actions) runner application installed - that is either hosted by GitHub, or self-hosted on your own machines.

This whole **workflow** including the **event** trigger and the **runner** on which the **workflow** will run in are specified and detailed using a workflow `.yml` file that is saved inside a directory named `.github` within your GitHub repository in which you want to use [GitHub Actions](https://docs.github.com/en/actions) on.

Following are different [GitHub Actions](https://docs.github.com/en/actions) workflows with their corresponding `.yml` files that illustrate various configurations in which [GitHub Actions](https://docs.github.com/en/actions) can be implemented or has been implemented within EHA.

<!--- INSERT IMAGE OF THE COMPONENTS HERE --->

## Using containers in GitHub Actions workflow

A **container** is a standard unit of software that packages up code and all its dependencies so the application runs quickly and reliably from one computing environment to another.

**Containers** can be used within a [GitHub Actions](https://docs.github.com/en/actions) workflow and can be specified either at the **job** level or at the **step** level. If specified at the **job** level, all the **steps** within that **job** will be run inside that container. When specified at the **steps** level, different containers can be used for each **step**.

The GitHub repository called `container-template` (see https://github.com/ecohealthalliance/container-template) has examples of [GitHub Actions](https://docs.github.com/en/actions) workflows that uses a container that packages up the most recent version of R and all its dependencies. 

The example/template workflows can be found inside the `.github` folder.

### Containerised GitHub Actions at the job level running on GitHub runners

The basic [GitHub Actions](https://docs.github.com/en/actions) workflow that uses a container with the image of the most recent version of R and that runs on GitHub runners is specified as follows:

```yaml
name: test-base-container-template

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
    branches:
      - '*'
      
jobs:
  test-base-container-template:
    runs-on: ubuntu-latest
    container:
      image: rocker/r-ver:4.1.1
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Get container id
        run: |
          cat /proc/self/cgroup | head -1 | tr --delete '10:memory:/docker/'
      
      - name: Get container id in R
        run: |
          source("R/test_base.R")
          print_container_id()
        shell: Rscript {0}
```

This workflow performs an action of retrieving the container ID via terminal and using R as a way to test that the actions are performed within a container that has the most recent version of R installed. The container is setup at the **job** level and as such each step is performed within the specified container. This workflow is triggered by any push to the main/master branch of the repository and can be manually run from the GitHub Actions page of the repository.

### Containerised GitHub Actions at the job level running on self-hosted runners

The same basic [GitHub Actions](https://docs.github.com/en/actions) workflow above can also be run on self-hosted EHA runners using the following workflow specifications:

```yaml
name: test-base-container-template-aegypti

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
    branches:
      - '*'
      
jobs:
  test-base-container-template-aegypti:
    runs-on: [self-hosted, linux, x64, onprem-aegypti]
    container:
      image: rocker/r-ver:4.1.1
    
    steps:
      - uses: actions/checkout@v2

      - name: Get container id
        run: |
          cat /proc/self/cgroup | head -1 | tr --delete '10:memory:/docker/'
      
      - name: Get container id in R
        run: |
          source("R/test_base.R")
          print_container_id()
        shell: Rscript {0}
```

Here, we specify the workflow to run on a self-hosted runner that is installed in one of our compute machines (in this case `aegypti`). We use the following tags `[self-hosted, linux, x64, onprem-aegypti]` to identify the self-hosted runner we want to use.

The self-hosted runners are ideal for workflows that contain sensitive information/data that we don't want to expose outside of the organisation and/or for workflows that require high performance computing.

