---
title: "EHA Modeling & Analytics Handbook"
subtitle: |
  "These aren't rules, just some things that we figured out."  -- [Michael Reno Harrel](https://www.youtube.com/watch?v=66VtriAxcyw) \
  Last edit `r as.character(as.Date(git2r::when(git2r::commits()[[1]])))` by `r git2r::commits()[[1]]$author$name`
site: bookdown::bookdown_site
github-repo: ecohealthalliance/eha-ma-handbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
favicon: "favicon.png"
params:
  data_librarian: "[Data Librarian](https://www.ecohealthalliance.org/personnel/collin-schwantes)"
  infrastructure_lead: "[Infrastructure Lead]( https://www.ecohealthalliance.org/personnel/robert-young)"
---

# Introduction {#introduction .unnumbered}

This handbook describes best practices and guidelines for project management,
organization, modeling and and programming we aim for our on the EHA Modeling &
Analytics team.

This is a living document. To make changes, just click the edit button
(<i class="fa fa-edit"></i>) at the top of the page. It will take you to the
source editor for the chapter on GitHub, where you can make edits and submit
your changes. Be sure to commit major [contributions](#contributions) to a new branch and open a pull request. 

In general, we aim to produce sound analyses that are:

-   Self-contained
-   Well-documented and communicated
-   Easily reproducible
-   Sharable
-   Version controlled

Together, these attributes help assure that our work is correct, can be built
off of and extended, meets requirements for sharing and publication, and can be
continued through staff turnover.

The tools we use to accomplish this are mostly, but not exclusively, based
around the R programming language and git version control. Other teams at EHA
use other tools (e.g., the technology team mostly uses Python and Javascript,
much of our work with partners is MS Office based).

The guidelines in the document represent an ideal we aim for but to not always
attain. Remember:

-   Best practices are always evolving.
-   Don't let the perfect be the enemy of the good.
-   Other teams and external partners have different workflows and we adjust as
    neccessary to collaborate.
-   Our goal is to do good science to advance conservation and human health, not
    be slick programmers.

You can find some slides from a previous presentation on this topic
[here](assets/selfish-reproducibility-NR-2016-01-26.pdf).

The philosophy and guidelines in this document owe an enormous amount to the
work of the [Software and Data Carpentry](http://software-carpentry.org/) and
[rOpenSci](http://ropensci.org/) organizations, and the work of [Hadley
Wickham](http://hadley.nz/) and [Jenny Bryan](http://www.stat.ubc.ca/~jenny/).
You'll find many links to their work in this handbook.
