# References

[Paperpile](https://paperpile.com/) is an excellent tool for sharing and keeping
track of research papers, and it is fully integrated into Google Docs -- which
means you can easily add citations on shared documents. Many teams and projects
use Paperpile to organize and share references. If you need a paperpile account,
request a key from Megan Walsh. Be sure to associate the Paperpile with your EHA
Google account, not a personal one.

Many people in the office use [EndNote](https://endnote.com/) which can be offline on your desktop or online. 
A nice feature of Endnote is the traveling libraries export from word documents. You 
will need a license for this, so contact Megan Walsh. 

## Converting Paperpile Citations in Google Docs to Endnote Citations in MS Word

There are some situations where you may need to convert a Google Doc with
Paperpile citations into a Microsoft Word Document with Endnote citations.
Luckily, Paperpile has a detailed guide to walk you through the process.

**But first, you must properly install the Paperpile Google Docs Add-on!**

-   Note: You may already have the Google Chrome Paperpile Extension installed
    and be using it to create citations in your Google Doc, but you need the
    Google Docs Add-on for proper exporting.

To install this addon, follow the links from Paperpile's [website dedicated to
Google Docs](https://paperpile.com/blog/free-google-docs-add-on/).

Now, when you open a document in Google Docs, you should see both menus for
*Addons* and *Paperpile*. In order to begin Step 1 of Paperpile's Endnote Guide,
you need to access the add-on sidebar:

-   Go to *Addons* $\rightarrow$ *Paperpile* $\rightarrow$ *Manage Citations*
    and the Paperpile side-bar will appear
-   **Don't try to export or mess around with the *Paperpile* menu option (or P
    symbol) -- they won't help you!**

Once you have the add-on sidebar open, you can follow Paperpile's [detailed
guide](http://forum.paperpile.com/t/guide-export-a-google-document-to-word-endnote/777).

-   Note: depending on your operating system and your edition of Microsoft Word,
    some of the Word menus may appear slightly different than the ones depicted
    in Paperpile's guide. However, the Paperpile images included in the guide
    should look *exactly the same*.

