# Tips, Tricks, and Workarounds for Survey Planning and Implementation

This chapter is a compilation of tips, tricks and workarounds in survey planning and implementation. The information here is collected from discussions, and questions and answers between teams and individuals within EHA on various topics and approaches that have helped when planning and implementating surveys.

## Offline navigation

There have been occasions wherein specific location/s identified for a survey/study require the survey/study team to locate and navigate to them. This can either be due to the everchanging name and/or structure of the location, or that the only information the survey/study team has is a geocoordinate of the specific sampling location. In such instances, being able to navigate to the sampling locatiom is extremely helpful and are usually aided by already ubiquitous navigation tools/maps available through our mobile phones. These tools/maps usually require the user to be online (either through a data connection through the mobile phone or on WiFi). However, such connectivity is not always available particularly when field work and data collection is in a remote area. Following are some tools/apps that help solve this problem as they offer offline navigation.

### Maps.me

[Maps.me](https://maps.me/) is a mobile app for Android, iOS and BlackBerry that provides offline maps using OpenStreetMap data. It was formerly known as MapsWithMe. [Maps.me](https://maps.me/) is free to use but has a lot of advertisement shown within the application itself. [Maps.me](https://maps.me/) is used in the same way as any navigation device that allows the user to search for an area of interest. Anything from name of location, keywords or GPS coordinates can be provided within the application's search bar in order to initiate a search. The searched location is then shown on the map used by the application to which the user can choose to navigate to. The application will then provide turn-by-turn navigation to the selected location. Both the search and the navigation does not require the device used to be on the internet.

If a user has an Open Data Kit survey form, it can be designed in such a way that a link to the app can be created from within the form and the GPS coordinate of a specific location can then be entered to search and/or navigate to a location. Detailed explanation on how this can be done can be found [here](https://docs.getodk.org/launch-apps-from-collect/).

### Sygic GPS Navigation

[Sygic GPS Navigation](https://www.sygic.com/gps-navigation) is another popular
application for offline navigation. Unlike [Maps.me](https://maps.me/), [Sygic
GPS Navigation](https://www.sygic.com/gps-navigation) requires purchase to avail
of its more advanced/professional features most of which are the ones that would
be helpful for the problem described above. [Sygic GPS
Navigation](https://www.sygic.com/gps-navigation) starts out at 4.66 Euros a
month for a three month subscription and the monthly cost goes down the longer
the period of subscription that is purchased.
